### ISSUE TITLE
practica-final-de-hilos-equipo-ybjs

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/practica-final-de-hilos-equipo-ybjs#2]
[Reporte de Práctica Final -Hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-equipo-ybjs/files/6533154/Reporte.de.Practica.Final.-Hilos.pdf)

**Comment by Anthony4523** [comment]
Calificación: 18

La práctica es la misma que se realizó de manera individual.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
